### ISSUE TITLE
CollectionView Header

### ISSUE THREAD

**Issue by angelru** [luismts/StickyHeader#1]
In this article:
https://luismts.com/en/sticky-header-xamarin-forms/

 You say that you can also put a header to the CollectionView, but I can't combine it, can you give an example?

Thank you

**Comment by luismts** [comment]
The link is this one:
https://luismts.com/stickyheader-xamarin-forms/

Did you see the repo?

Here the header:
https://github.com/luismts/StickyHeader/blob/883ddf1094824d5821794adc5b051efa4b3eda19/StickyHeader/StickyHeader/Views/MainPage.xaml#L40

**Comment by angelru** [comment]
I thought it could be combined with the Header of the CollectionView, this one is not showing me. `<CollectionView.Header>`

`Note: There is a limitation. The control automatically creates a Header within the CollectionView. If you create a header it will be overwritten by our code and add a BoxView to simulate the margin of the control. If you want to use a Header within the CollectionView, just set a fixed height to your Header and your row within the Grid where you position the header.`

If you can show me an example, I have set a fixed height and row size and the Header of the CollectionView is not displayed


cc: @luismts

**Comment by luismts** [comment]
Sorry, I dont have enough time to show you an example. You have to figure it out on your own. 

When I say fixed height I mean in the control.

https://github.com/luismts/StickyHeader/blob/883ddf1094824d5821794adc5b051efa4b3eda19/StickyHeader/StickyHeader/Controls/CustomCollectionView.cs#L43
